import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettier from "eslint-config-prettier/flat";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Constitution, Principle V. Scoping to src/ leaves the exempt files free by
  // construction: root tooling configs run outside the app.
  {
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["src/config/**"],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector:
            "MemberExpression[object.name='process'][property.name='env']",
          message:
            "Read configuration from @/config, not process.env (Constitution, Principle V).",
        },
      ],
    },
  },
  // src/server is the portable core (MC-008): nothing framework-specific may enter it.
  {
    files: ["src/server/**/*.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: ["next", "next-auth", "react", "react-dom", "server-only"],
          patterns: ["next/*", "next-auth/*"],
        },
      ],
    },
  },
  // Last, so it wins: turns off every rule Prettier already owns.
  prettier,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Playwright artifacts.
    "test-results/**",
    "playwright-report/**",
    "blob-report/**",
    "playwright/.cache/**",
    // Prisma Client, regenerated by the postinstall hook.
    "prisma/generated/**",
  ]),
]);

export default eslintConfig;
