import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettier from "eslint-config-prettier/flat";

const PROCESS_ENV = {
  selector: "MemberExpression[object.name='process'][property.name='env']",
  message:
    "Read configuration from @/config, not process.env (Constitution, Principle V).",
};

const DATE_FORMATTING_MESSAGE =
  "Format dates and times with useFormatInstant from @/i18n/use-format-instant (spec 004, FR-015).";

const DATE_FORMATTING = [
  {
    selector:
      "CallExpression[callee.property.name=/^(dateTime|dateTimeRange|relativeTime|toLocaleDateString|toLocaleTimeString|toLocaleString)$/]",
    message: DATE_FORMATTING_MESSAGE,
  },
  {
    selector:
      "NewExpression[callee.object.name='Intl'][callee.property.name=/^(DateTimeFormat|RelativeTimeFormat)$/]",
    message: DATE_FORMATTING_MESSAGE,
  },
];

const ROUTE_PATHS_MESSAGE =
  "Import page and API paths from @/lib/routes (Constitution, Principle VIII).";

const ROUTE_PATHS = [
  { selector: "Literal[value=/^\\/[a-z]/]", message: ROUTE_PATHS_MESSAGE },
  {
    selector: "TemplateElement[value.raw=/^\\/[a-z]/]",
    message: ROUTE_PATHS_MESSAGE,
  },
];

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Constitution, Principle V. Scoping to src/ leaves the exempt files free by
  // construction: root tooling configs run outside the app.
  {
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["src/config/**"],
    rules: {
      "no-restricted-syntax": ["error", PROCESS_ENV],
    },
  },
  // Constitution, Principle VIII. Tests keep literal paths: they must fail when an address changes.
  {
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["src/config/**", "src/**/*.test.{ts,tsx}", "src/lib/routes.ts"],
    rules: {
      "no-restricted-syntax": ["error", PROCESS_ENV, ...ROUTE_PATHS],
    },
  },
  // Spec 004, FR-016: screen code formats dates only through useFormatInstant.
  // src/server is browser-less output, decided by the feature that adds it.
  {
    files: ["src/**/*.{ts,tsx}"],
    ignores: [
      "src/config/**",
      "src/server/**",
      "src/**/*.test.{ts,tsx}",
      "src/i18n/use-format-instant.ts",
      "src/lib/routes.ts",
    ],
    rules: {
      // Repeats the rules above: a later no-restricted-syntax replaces an earlier one instead of merging.
      "no-restricted-syntax": [
        "error",
        PROCESS_ENV,
        ...DATE_FORMATTING,
        ...ROUTE_PATHS,
      ],
    },
  },
  // src/server is the portable core (MC-008): nothing framework-specific may enter it.
  {
    files: ["src/server/**/*.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: ["next", "next-auth", "react", "react-dom", "server-only"],
          patterns: ["next/*", "next-auth/*"],
        },
      ],
    },
  },
  // Last, so it wins: turns off every rule Prettier already owns.
  prettier,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Playwright artifacts.
    "test-results/**",
    "playwright-report/**",
    "blob-report/**",
    "playwright/.cache/**",
    // Prisma Client, regenerated by the postinstall hook.
    "prisma/generated/**",
  ]),
]);

export default eslintConfig;
